---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  kustomize.buildOptions: --enable-alpha-plugins --enable-helm
  #url: https://argocd.k3s.sbriggs.io 
  # https://argo-cd.readthedocs.io/en/release-2.4/faq/#why-is-my-application-still-outofsync-immediately-after-a-successful-sync
  # https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/argocd-cm.yaml#L235
  application.instanceLabelKey: argocd.argoproj.io/instance
  #repository.credentials: |
  #  - sshPrivateKeySecret:
  #      name: ssh-key
  #      key: id_rsa
  #    url: git@github.com:mr0xb/homelab.git
  #    path: IAC/application-deployment
  repositories: |
    - name: github-app-deploy
      url: git@github.com:mr0xb/homelab.git
      type: git
      sshPrivateKeySecret:
        name: ssh-key
        key: id_rsa
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
data:
  server.insecure: "true"
  server.staticassets: "/shared/app"
