---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.5.0/manifests/install.yaml
  #- ingress.yaml
  #- services.yaml
  - namespace.yaml

patches:
  - statefulset.yaml
  - configmap.yaml
  - sopsSecretsGenerator.yaml

patchesStrategicMerge:
  - import-gpg-key.yaml

generators:
  - github-priv-key.sops.yaml
  - sops-key.sops.yaml
