apiVersion: goabout.com/v1beta1
kind: SopsSecretGenerator
metadata:
  name: argocd-secrets
  namespace: argocd
type: Opaque
files:
  - ../../secrets/github-priv-key.sops.yaml
  - ../../secrets/sops-key.sops.yaml
